run:
	uv run python new_intake.py ProcessAllCSVs
	# python new_intake.py ProcessAllCSVs

debug:
	uv run python new_intake.py ProcessAllCSVs --output-directory "working"
	uv run python new_intake.py GenerateManifest --output-directory "working"
	# python new_intake.py ProcessAllCSVs --output-directory "working"
	# python new_intake.py GenerateManifest --output-directory "working"
