run:
	uv run python pipeline.py ProcessAllCSVs 

debug:
	uv run python pipeline.py ProcessAllCSVs --output-directory "working1" >debug.log 2>debug.log
	# python pipeline.py ProcessAllCSVs --output-directory "working"
	# python pipeline.py GenerateManifest --output-directory "working"
